### ISSUE TITLE
Don't call Promise.longStackTraces()

### ISSUE THREAD

**Issue by alexgorbatchev** [geekingfrog/zeninjector#8]
I think it's up to the user to call `Promise.longStackTraces()` as you do [here](https://github.com/geekingfrog/zeninjector/blob/master/lib/promise.js#L2). It has [significant performance](https://github.com/petkaantonov/bluebird/blob/master/API.md#promiselongstacktraces---void) implications.

**Comment by geekingfrog** [comment]
In this case, how the user should call it?
Should I expose a function to call it? Or an option to pass when the container is constructed? I agree it shouldn't be on by default.

**Comment by alexgorbatchev** [comment]
I'm a bit confused by the `promise.js` file in general. Why not simply require `bluebird` directly? If user installs `bluebird` in their project, assuming compatible version, it will be shared and they can call `Promise.whatever...` themselves.

IMO, change `bluebird` version to `^1.2` and get rid of `promise.js`.

**Comment by geekingfrog** [comment]
The `promise.js` is because of [this doc](https://github.com/petkaantonov/bluebird#for-library-authors) from bluebird. To use long stack traces, a single copy of bluebird should be used, thus this file.
I'm going to update the lib shortly, with bluebird as `^2.1`, and add an option during construction to enable long stack traces.

**Comment by geekingfrog** [comment]
I upgraded `bluebird` in 43e114aa7dac7fdff814902c20ebca3f0db7afa8 and completely removed the long stack traces support. I'll re-add them later maybe if I find a good solution for this. @alexgorbatchev please open a new issue if you need the long stack trace support. For the moment, it's the easiest solution to use the library without any performances issue.

**Comment by alexgorbatchev** [comment]
Great! Thank you!
