### ISSUE TITLE
Cache dependency resolution

### ISSUE THREAD

**Issue by alexgorbatchev** [geekingfrog/zeninjector#9]
I feel dependency resolution should be cached. Function arguments are unlikely to change and caching of the map and injections results could significantly improve behavior. I'm specifically referring to [lib/container.js#L208-L214](https://github.com/geekingfrog/zeninjector/blob/master/lib/container.js#L208-L214)

What do you think?

**Comment by geekingfrog** [comment]
I think it's already cached. When calling `resolve`, see [container.js#L140](https://github.com/geekingfrog/zeninjector/blob/master/lib/container.js#L140)

**Comment by alexgorbatchev** [comment]
Great, missed that one :)
